run: Exercice_4_classe_point. o POINT.o
	g++ −o Exercice_4_classe_point Exercice_4_classe_point. o POINT.o
	
Exercice_4_classe_point.o: Exercice_4_classe_point.cc a POINT. h
	g++ −Wall −c Exercice_4_classe_point.cc

POINT.o: POINT.cc POINT.h
	g++ −Wall −c POINT.cc
